export const PDF_LABELS = {
  en: {
    brand: "FORESEE",
    tagline: "AI Decision Intelligence",
    reportTitle: "FORESEE Report",
    page: "Page",
    date: "Date",
    language: "Language",
    dataQuality: "Data Quality",
    situation: "Situation",
    executiveSummary: "Executive Summary",
    bottomLine: "Bottom Line",
    knownFacts: "Known Facts",
    assumptions: "Assumptions",
    unknowns: "Unknowns",
    keyVariables: "Key Variables",
    whatCouldChange: "What Could Change The Forecast?",
    scenarioMap: "Possible Scenarios",
    scenarioDetails: "Scenario Details",
    bestCase: "Best Case",
    mostLikely: "Most Likely",
    worstCase: "Worst Case",
    likelihood: "Likelihood",
    confidence: "Confidence",
    impact: "Impact",
    whyItCouldHappen: "Why it could happen",
    whatWouldTrigger: "What would trigger it",
    earlyWarningSigns: "Early warning signs",
    potentialImpact: "Potential impact",
    recommendedResponse: "Recommended response",
    decisionSupport: "Decision Support",
    recommendedAction: "Recommended Action",
    ifThen: "If / Then",
    updateHistory: "Forecast Updates",
    newInformation: "New information",
    outcome: "What Actually Happened?",
    forecastVsReality: "Forecast vs. Reality",
    matchedScenario: "Closest matching scenario",
    whatWentRight: "What the forecast got right",
    whatWasMissed: "What the forecast missed",
    wrongAssumptions: "Assumptions that turned out wrong",
    outcomeNotRecorded: "Outcome not recorded yet.",
    notAvailable: "Not available",
    behavioralVariables: "Behavioral factors",
    externalVariables: "External factors",
    controllableVariables: "Factors you can influence",
    uncontrollableVariables: "Factors outside your control",
  },
  ar: {
    brand: "فورسي",
    tagline: "ذكاء اصطناعي لاتخاذ القرار",
    reportTitle: "تقرير فورسي",
    page: "صفحة",
    date: "التاريخ",
    language: "اللغة",
    dataQuality: "جودة البيانات",
    situation: "الموقف",
    executiveSummary: "الملخص التنفيذي",
    bottomLine: "الخلاصة",
    knownFacts: "الحقائق المعروفة",
    assumptions: "الافتراضات",
    unknowns: "المجاهيل",
    keyVariables: "المتغيرات الأساسية",
    whatCouldChange: "شو ممكن يغيّر التوقع؟",
    scenarioMap: "السيناريوهات المحتملة",
    scenarioDetails: "تفاصيل السيناريوهات",
    bestCase: "أفضل احتمال",
    mostLikely: "الاحتمال الأرجح",
    worstCase: "أسوأ احتمال",
    likelihood: "الاحتمالية",
    confidence: "درجة الثقة",
    impact: "الأثر",
    whyItCouldHappen: "ليش ممكن يصير",
    whatWouldTrigger: "شو ممكن يحفزه",
    earlyWarningSigns: "إشارات إنذار مبكر",
    potentialImpact: "الأثر المحتمل",
    recommendedResponse: "الاستجابة الموصى بها",
    decisionSupport: "دعم القرار",
    recommendedAction: "التوصية الأساسية",
    ifThen: "إذا / بعدين",
    updateHistory: "تحديثات التوقع",
    newInformation: "المعلومة الجديدة",
    outcome: "شو صار فعلاً؟",
    forecastVsReality: "التوقع مقابل الواقع",
    matchedScenario: "أقرب سيناريو مطابق",
    whatWentRight: "شو التوقع كان صحيح فيه",
    whatWasMissed: "شو التوقع فوته",
    wrongAssumptions: "افتراضات طلعت غلط",
    outcomeNotRecorded: "لسا ما اتسجلت نتيجة.",
    notAvailable: "غير متوفر",
    behavioralVariables: "عوامل سلوكية",
    externalVariables: "عوامل خارجية",
    controllableVariables: "عوامل بتقدر تأثر فيها",
    uncontrollableVariables: "عوامل خارج سيطرتك",
  },
} as const;

export type PdfLocale = "en" | "ar";
export type PdfLabelSet = (typeof PDF_LABELS)[PdfLocale];
