export const PDF_LABELS = {
  en: {
    languageName: "English",
    brand: "FORESEE",
    tagline: "AI Decision Intelligence",
    reportTitle: "FORESEE Report",
    page: "Page",
    date: "Date",
    language: "Language",
    dataQuality: "Data Quality",
    situation: "Situation",
    executiveSummary: "Executive Summary",
    bottomLine: "Bottom Line",
    knownFacts: "Known Facts",
    assumptions: "Assumptions",
    unknowns: "Unknowns",
    keyVariables: "Key Variables",
    whatCouldChange: "What Could Change The Forecast?",
    limitsOfForecast: "What This Forecast Can't Determine",
    scenarioMap: "Possible Scenarios",
    scenarioDetails: "Scenario Details",
    bestCase: "Best Case",
    mostLikely: "Most Likely",
    worstCase: "Worst Case",
    positiveOutcome: "If This Goes Well",
    mixedOutcome: "Mixed Outcome",
    negativeOutcome: "If This Goes Poorly",
    decisionPath: "Path",
    likelihood: "Likelihood",
    confidence: "Confidence",
    impact: "Impact",
    whyItCouldHappen: "Why it could happen",
    whatWouldTrigger: "What would trigger it",
    earlyWarningSigns: "Early warning signs",
    potentialImpact: "Potential impact",
    recommendedResponse: "Recommended response",
    decisionSupport: "Decision Support",
    recommendedAction: "Recommended Action",
    ifThen: "If / Then",
    updateHistory: "Forecast Updates",
    newInformation: "New information",
    outcome: "What Actually Happened?",
    forecastVsReality: "Forecast vs. Reality",
    matchedScenario: "Closest matching scenario",
    whatWentRight: "What the forecast got right",
    whatWasMissed: "What the forecast missed",
    wrongAssumptions: "Assumptions that turned out wrong",
    outcomeNotRecorded: "Outcome not recorded yet.",
    notAvailable: "Not available",
    behavioralVariables: "Behavioral factors",
    externalVariables: "External factors",
    controllableVariables: "Factors you can influence",
    uncontrollableVariables: "Factors outside your control",
  },
  ar: {
    languageName: "العربية",
    brand: "فورسي",
    tagline: "ذكاء اصطناعي لاتخاذ القرار",
    reportTitle: "تقرير فورسي",
    page: "صفحة",
    date: "التاريخ",
    language: "اللغة",
    dataQuality: "جودة البيانات",
    situation: "الموقف",
    executiveSummary: "الملخص التنفيذي",
    bottomLine: "الخلاصة",
    knownFacts: "الحقائق المعروفة",
    assumptions: "الافتراضات",
    unknowns: "المعلومات المجهولة",
    keyVariables: "المتغيرات الأساسية",
    whatCouldChange: "ما الذي قد يغيّر التوقع؟",
    limitsOfForecast: "ما لا يستطيع هذا التوقع تحديده",
    scenarioMap: "السيناريوهات المحتملة",
    scenarioDetails: "تفاصيل السيناريوهات",
    bestCase: "أفضل سيناريو",
    mostLikely: "السيناريو الأرجح",
    worstCase: "أسوأ سيناريو",
    positiveOutcome: "لو سار هذا بشكل جيد",
    mixedOutcome: "نتيجة مختلطة",
    negativeOutcome: "لو سار هذا بشكل سيئ",
    decisionPath: "المسار",
    likelihood: "الاحتمال",
    confidence: "درجة الثقة",
    impact: "التأثير",
    whyItCouldHappen: "لماذا قد يحدث؟",
    whatWouldTrigger: "ما الذي قد يجعله أكثر احتمالاً؟",
    earlyWarningSigns: "إشارات الإنذار المبكر",
    potentialImpact: "التأثير المحتمل",
    recommendedResponse: "الاستجابة المقترحة",
    decisionSupport: "دعم القرار",
    recommendedAction: "الإجراء المقترح",
    ifThen: "إذا / حينئذ",
    updateHistory: "تحديثات التوقع",
    newInformation: "المعلومة الجديدة",
    outcome: "ماذا حدث فعلياً؟",
    forecastVsReality: "التوقع مقابل الواقع",
    matchedScenario: "أقرب سيناريو مطابق",
    whatWentRight: "ما الذي كان التوقع محقاً فيه",
    whatWasMissed: "ما الذي فات التوقع",
    wrongAssumptions: "افتراضات تبيّن أنها غير صحيحة",
    outcomeNotRecorded: "لم تُسجَّل نتيجة بعد.",
    notAvailable: "غير متوفر",
    behavioralVariables: "عوامل سلوكية",
    externalVariables: "عوامل خارجية",
    controllableVariables: "عوامل يمكنك التأثير فيها",
    uncontrollableVariables: "عوامل خارج سيطرتك",
  },
  es: {
    languageName: "Español",
    brand: "FORESEE",
    tagline: "Inteligencia de decisión con IA",
    reportTitle: "Informe de Foresee",
    page: "Página",
    date: "Fecha",
    language: "Idioma",
    dataQuality: "Calidad de los datos",
    situation: "Situación",
    executiveSummary: "Resumen ejecutivo",
    bottomLine: "Conclusión",
    knownFacts: "Hechos conocidos",
    assumptions: "Suposiciones",
    unknowns: "Incógnitas",
    keyVariables: "Variables clave",
    whatCouldChange: "¿Qué podría cambiar el pronóstico?",
    limitsOfForecast: "Lo que este pronóstico no puede determinar",
    scenarioMap: "Escenarios posibles",
    scenarioDetails: "Detalles de los escenarios",
    bestCase: "Mejor caso",
    mostLikely: "Escenario más probable",
    worstCase: "Peor caso",
    positiveOutcome: "Si esto va bien",
    mixedOutcome: "Resultado mixto",
    negativeOutcome: "Si esto va mal",
    decisionPath: "Camino",
    likelihood: "Probabilidad",
    confidence: "Confianza",
    impact: "Impacto",
    whyItCouldHappen: "Por qué podría ocurrir",
    whatWouldTrigger: "Qué lo haría más probable",
    earlyWarningSigns: "Señales de alerta temprana",
    potentialImpact: "Impacto potencial",
    recommendedResponse: "Respuesta recomendada",
    decisionSupport: "Apoyo a la decisión",
    recommendedAction: "Acción recomendada",
    ifThen: "Si / Entonces",
    updateHistory: "Actualizaciones del pronóstico",
    newInformation: "Nueva información",
    outcome: "¿Qué pasó en realidad?",
    forecastVsReality: "Pronóstico frente a realidad",
    matchedScenario: "Escenario más parecido",
    whatWentRight: "Lo que el pronóstico acertó",
    whatWasMissed: "Lo que el pronóstico no consideró",
    wrongAssumptions: "Suposiciones que resultaron incorrectas",
    outcomeNotRecorded: "Aún no se ha registrado un resultado.",
    notAvailable: "No disponible",
    behavioralVariables: "Factores conductuales",
    externalVariables: "Factores externos",
    controllableVariables: "Factores que puedes influir",
    uncontrollableVariables: "Factores fuera de tu control",
  },
  fr: {
    languageName: "Français",
    brand: "FORESEE",
    tagline: "Intelligence de décision par IA",
    reportTitle: "Rapport Foresee",
    page: "Page",
    date: "Date",
    language: "Langue",
    dataQuality: "Qualité des données",
    situation: "Situation",
    executiveSummary: "Résumé exécutif",
    bottomLine: "L'essentiel",
    knownFacts: "Faits connus",
    assumptions: "Suppositions",
    unknowns: "Inconnues",
    keyVariables: "Variables clés",
    whatCouldChange: "Qu'est-ce qui pourrait changer la prévision ?",
    limitsOfForecast: "Ce que cette prévision ne peut pas déterminer",
    scenarioMap: "Scénarios possibles",
    scenarioDetails: "Détails des scénarios",
    bestCase: "Meilleur scénario",
    mostLikely: "Scénario le plus probable",
    worstCase: "Pire scénario",
    positiveOutcome: "Si cela se passe bien",
    mixedOutcome: "Résultat mitigé",
    negativeOutcome: "Si cela se passe mal",
    decisionPath: "Option",
    likelihood: "Probabilité",
    confidence: "Confiance",
    impact: "Impact",
    whyItCouldHappen: "Pourquoi cela pourrait arriver",
    whatWouldTrigger: "Ce qui le rendrait plus probable",
    earlyWarningSigns: "Signes avant-coureurs",
    potentialImpact: "Impact potentiel",
    recommendedResponse: "Réponse recommandée",
    decisionSupport: "Aide à la décision",
    recommendedAction: "Action recommandée",
    ifThen: "Si / Alors",
    updateHistory: "Mises à jour de la prévision",
    newInformation: "Nouvelle information",
    outcome: "Que s'est-il réellement passé ?",
    forecastVsReality: "Prévision face à la réalité",
    matchedScenario: "Scénario le plus proche",
    whatWentRight: "Ce que la prévision a bien anticipé",
    whatWasMissed: "Ce que la prévision n'a pas anticipé",
    wrongAssumptions: "Suppositions qui se sont révélées fausses",
    outcomeNotRecorded: "Aucun résultat enregistré pour l'instant.",
    notAvailable: "Non disponible",
    behavioralVariables: "Facteurs comportementaux",
    externalVariables: "Facteurs externes",
    controllableVariables: "Facteurs que vous pouvez influencer",
    uncontrollableVariables: "Facteurs hors de votre contrôle",
  },
  de: {
    languageName: "Deutsch",
    brand: "FORESEE",
    tagline: "KI-Entscheidungsintelligenz",
    reportTitle: "Foresee-Bericht",
    page: "Seite",
    date: "Datum",
    language: "Sprache",
    dataQuality: "Datenqualität",
    situation: "Situation",
    executiveSummary: "Zusammenfassung",
    bottomLine: "Kernaussage",
    knownFacts: "Bekannte Fakten",
    assumptions: "Annahmen",
    unknowns: "Unbekannte Faktoren",
    keyVariables: "Schlüsselfaktoren",
    whatCouldChange: "Was könnte die Prognose ändern?",
    limitsOfForecast: "Was diese Prognose nicht bestimmen kann",
    scenarioMap: "Mögliche Szenarien",
    scenarioDetails: "Szenariodetails",
    bestCase: "Bestmögliches Szenario",
    mostLikely: "Wahrscheinlichstes Szenario",
    worstCase: "Schlimmstmögliches Szenario",
    positiveOutcome: "Wenn es gut läuft",
    mixedOutcome: "Gemischtes Ergebnis",
    negativeOutcome: "Wenn es schlecht läuft",
    decisionPath: "Option",
    likelihood: "Wahrscheinlichkeit",
    confidence: "Vertrauensgrad",
    impact: "Auswirkung",
    whyItCouldHappen: "Warum es passieren könnte",
    whatWouldTrigger: "Was es wahrscheinlicher machen würde",
    earlyWarningSigns: "Frühwarnzeichen",
    potentialImpact: "Mögliche Auswirkung",
    recommendedResponse: "Empfohlene Reaktion",
    decisionSupport: "Entscheidungshilfe",
    recommendedAction: "Empfohlene Maßnahme",
    ifThen: "Wenn / Dann",
    updateHistory: "Aktualisierungen der Prognose",
    newInformation: "Neue Information",
    outcome: "Was ist tatsächlich passiert?",
    forecastVsReality: "Prognose vs. Realität",
    matchedScenario: "Am ehesten zutreffendes Szenario",
    whatWentRight: "Was die Prognose richtig eingeschätzt hat",
    whatWasMissed: "Was die Prognose übersehen hat",
    wrongAssumptions: "Annahmen, die sich als falsch erwiesen haben",
    outcomeNotRecorded: "Noch kein Ergebnis gespeichert.",
    notAvailable: "Nicht verfügbar",
    behavioralVariables: "Verhaltensfaktoren",
    externalVariables: "Externe Faktoren",
    controllableVariables: "Faktoren, die du beeinflussen kannst",
    uncontrollableVariables: "Faktoren außerhalb deiner Kontrolle",
  },
  it: {
    languageName: "Italiano",
    brand: "FORESEE",
    tagline: "Intelligenza decisionale con IA",
    reportTitle: "Rapporto Foresee",
    page: "Pagina",
    date: "Data",
    language: "Lingua",
    dataQuality: "Qualità dei dati",
    situation: "Situazione",
    executiveSummary: "Sintesi",
    bottomLine: "In sintesi",
    knownFacts: "Fatti noti",
    assumptions: "Supposizioni",
    unknowns: "Incognite",
    keyVariables: "Variabili chiave",
    whatCouldChange: "Cosa potrebbe cambiare la previsione?",
    limitsOfForecast: "Cosa questa previsione non può determinare",
    scenarioMap: "Scenari possibili",
    scenarioDetails: "Dettagli degli scenari",
    bestCase: "Scenario migliore",
    mostLikely: "Scenario più probabile",
    worstCase: "Scenario peggiore",
    positiveOutcome: "Se va bene",
    mixedOutcome: "Esito misto",
    negativeOutcome: "Se va male",
    decisionPath: "Opzione",
    likelihood: "Probabilità",
    confidence: "Affidabilità",
    impact: "Impatto",
    whyItCouldHappen: "Perché potrebbe accadere",
    whatWouldTrigger: "Cosa lo renderebbe più probabile",
    earlyWarningSigns: "Segnali di allarme precoce",
    potentialImpact: "Impatto potenziale",
    recommendedResponse: "Risposta consigliata",
    decisionSupport: "Supporto alla decisione",
    recommendedAction: "Azione consigliata",
    ifThen: "Se / Allora",
    updateHistory: "Aggiornamenti della previsione",
    newInformation: "Nuova informazione",
    outcome: "Cosa è successo realmente?",
    forecastVsReality: "Previsione vs realtà",
    matchedScenario: "Scenario più simile",
    whatWentRight: "Cosa la previsione ha azzeccato",
    whatWasMissed: "Cosa la previsione non ha considerato",
    wrongAssumptions: "Supposizioni rivelatesi sbagliate",
    outcomeNotRecorded: "Nessun esito ancora registrato.",
    notAvailable: "Non disponibile",
    behavioralVariables: "Fattori comportamentali",
    externalVariables: "Fattori esterni",
    controllableVariables: "Fattori che puoi influenzare",
    uncontrollableVariables: "Fattori fuori dal tuo controllo",
  },
  pt: {
    languageName: "Português",
    brand: "FORESEE",
    tagline: "Inteligência de decisão com IA",
    reportTitle: "Relatório Foresee",
    page: "Página",
    date: "Data",
    language: "Idioma",
    dataQuality: "Qualidade dos dados",
    situation: "Situação",
    executiveSummary: "Resumo executivo",
    bottomLine: "Conclusão",
    knownFacts: "Fatos conhecidos",
    assumptions: "Suposições",
    unknowns: "Incógnitas",
    keyVariables: "Variáveis-chave",
    whatCouldChange: "O que poderia mudar a previsão?",
    limitsOfForecast: "O que esta previsão não consegue determinar",
    scenarioMap: "Cenários possíveis",
    scenarioDetails: "Detalhes dos cenários",
    bestCase: "Melhor cenário",
    mostLikely: "Cenário mais provável",
    worstCase: "Pior cenário",
    positiveOutcome: "Se isso for bem",
    mixedOutcome: "Resultado misto",
    negativeOutcome: "Se isso for mal",
    decisionPath: "Caminho",
    likelihood: "Probabilidade",
    confidence: "Confiança",
    impact: "Impacto",
    whyItCouldHappen: "Por que poderia acontecer",
    whatWouldTrigger: "O que o tornaria mais provável",
    earlyWarningSigns: "Sinais de alerta precoce",
    potentialImpact: "Impacto potencial",
    recommendedResponse: "Resposta recomendada",
    decisionSupport: "Apoio à decisão",
    recommendedAction: "Ação recomendada",
    ifThen: "Se / Então",
    updateHistory: "Atualizações da previsão",
    newInformation: "Nova informação",
    outcome: "O que realmente aconteceu?",
    forecastVsReality: "Previsão vs. realidade",
    matchedScenario: "Cenário mais parecido",
    whatWentRight: "O que a previsão acertou",
    whatWasMissed: "O que a previsão não considerou",
    wrongAssumptions: "Suposições que se mostraram incorretas",
    outcomeNotRecorded: "Ainda não há resultado registrado.",
    notAvailable: "Não disponível",
    behavioralVariables: "Fatores comportamentais",
    externalVariables: "Fatores externos",
    controllableVariables: "Fatores que você pode influenciar",
    uncontrollableVariables: "Fatores fora do seu controle",
  },
} as const;

export type PdfLocale = "en" | "ar" | "es" | "fr" | "de" | "it" | "pt";
export type PdfLabelSet = (typeof PDF_LABELS)[PdfLocale];
