export const PDF_LABELS = {
  en: {
    brand: "FORESEE",
    tagline: "AI Decision Intelligence",
    reportTitle: "FORESEE Report",
    page: "Page",
    date: "Date",
    language: "Language",
    dataQuality: "Data Quality",
    situation: "Situation",
    executiveSummary: "Executive Summary",
    bottomLine: "Bottom Line",
    knownFacts: "Known Facts",
    assumptions: "Assumptions",
    unknowns: "Unknowns",
    keyVariables: "Key Variables",
    whatCouldChange: "What Could Change The Forecast?",
    limitsOfForecast: "What This Forecast Can't Determine",
    scenarioMap: "Possible Scenarios",
    scenarioDetails: "Scenario Details",
    bestCase: "Best Case",
    mostLikely: "Most Likely",
    worstCase: "Worst Case",
    positiveOutcome: "If This Goes Well",
    mixedOutcome: "Mixed Outcome",
    negativeOutcome: "If This Goes Poorly",
    decisionPath: "Path",
    likelihood: "Likelihood",
    confidence: "Confidence",
    impact: "Impact",
    whyItCouldHappen: "Why it could happen",
    whatWouldTrigger: "What would trigger it",
    earlyWarningSigns: "Early warning signs",
    potentialImpact: "Potential impact",
    recommendedResponse: "Recommended response",
    decisionSupport: "Decision Support",
    recommendedAction: "Recommended Action",
    ifThen: "If / Then",
    updateHistory: "Forecast Updates",
    newInformation: "New information",
    outcome: "What Actually Happened?",
    forecastVsReality: "Forecast vs. Reality",
    matchedScenario: "Closest matching scenario",
    whatWentRight: "What the forecast got right",
    whatWasMissed: "What the forecast missed",
    wrongAssumptions: "Assumptions that turned out wrong",
    outcomeNotRecorded: "Outcome not recorded yet.",
    notAvailable: "Not available",
    behavioralVariables: "Behavioral factors",
    externalVariables: "External factors",
    controllableVariables: "Factors you can influence",
    uncontrollableVariables: "Factors outside your control",
  },
  ar: {
    brand: "فورسي",
    tagline: "ذكاء اصطناعي لاتخاذ القرار",
    reportTitle: "تقرير فورسي",
    page: "صفحة",
    date: "التاريخ",
    language: "اللغة",
    dataQuality: "جودة البيانات",
    situation: "الموقف",
    executiveSummary: "الملخص التنفيذي",
    bottomLine: "الخلاصة",
    knownFacts: "الحقائق المعروفة",
    assumptions: "الافتراضات",
    unknowns: "المعلومات المجهولة",
    keyVariables: "المتغيرات الأساسية",
    whatCouldChange: "ما الذي قد يغيّر التوقع؟",
    limitsOfForecast: "ما لا يستطيع هذا التوقع تحديده",
    scenarioMap: "السيناريوهات المحتملة",
    scenarioDetails: "تفاصيل السيناريوهات",
    bestCase: "أفضل سيناريو",
    mostLikely: "السيناريو الأرجح",
    worstCase: "أسوأ سيناريو",
    positiveOutcome: "لو سار هذا بشكل جيد",
    mixedOutcome: "نتيجة مختلطة",
    negativeOutcome: "لو سار هذا بشكل سيئ",
    decisionPath: "المسار",
    likelihood: "الاحتمال",
    confidence: "درجة الثقة",
    impact: "التأثير",
    whyItCouldHappen: "لماذا قد يحدث؟",
    whatWouldTrigger: "ما الذي قد يجعله أكثر احتمالاً؟",
    earlyWarningSigns: "إشارات الإنذار المبكر",
    potentialImpact: "التأثير المحتمل",
    recommendedResponse: "الاستجابة المقترحة",
    decisionSupport: "دعم القرار",
    recommendedAction: "الإجراء المقترح",
    ifThen: "إذا / حينئذ",
    updateHistory: "تحديثات التوقع",
    newInformation: "المعلومة الجديدة",
    outcome: "ماذا حدث فعلياً؟",
    forecastVsReality: "التوقع مقابل الواقع",
    matchedScenario: "أقرب سيناريو مطابق",
    whatWentRight: "ما الذي كان التوقع محقاً فيه",
    whatWasMissed: "ما الذي فات التوقع",
    wrongAssumptions: "افتراضات تبيّن أنها غير صحيحة",
    outcomeNotRecorded: "لم تُسجَّل نتيجة بعد.",
    notAvailable: "غير متوفر",
    behavioralVariables: "عوامل سلوكية",
    externalVariables: "عوامل خارجية",
    controllableVariables: "عوامل يمكنك التأثير فيها",
    uncontrollableVariables: "عوامل خارج سيطرتك",
  },
} as const;

export type PdfLocale = "en" | "ar";
export type PdfLabelSet = (typeof PDF_LABELS)[PdfLocale];
